apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: penny

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - valkey.yaml
  - api-deployment.yaml
  - api-service.yaml
  - web-deployment.yaml
  - web-service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: penny
  app.kubernetes.io/part-of: penny-platform

images:
  - name: penny-api
    newName: ghcr.io/madfam-io/penny/api
    newTag: latest
  - name: penny-web
    newName: ghcr.io/madfam-io/penny/web
    newTag: latest