# Cloudflare Workers Configuration
name = "penny-edge"
main = "workers/index.ts"
compatibility_date = "2024-01-01"
node_compat = true

# Account and deployment settings
account_id = "YOUR_ACCOUNT_ID"
workers_dev = false
route = { pattern = "penny.ai/*", zone_id = "YOUR_ZONE_ID" }

# R2 Buckets
[[r2_buckets]]
binding = "ARTIFACTS"
bucket_name = "penny-artifacts"
preview_bucket_name = "penny-artifacts-preview"

[[r2_buckets]]
binding = "UPLOADS"
bucket_name = "penny-uploads"
preview_bucket_name = "penny-uploads-preview"

[[r2_buckets]]
binding = "EXPORTS"
bucket_name = "penny-exports"
preview_bucket_name = "penny-exports-preview"

# KV Namespaces for edge caching
[[kv_namespaces]]
binding = "CACHE"
id = "YOUR_KV_NAMESPACE_ID"
preview_id = "YOUR_KV_PREVIEW_ID"

[[kv_namespaces]]
binding = "SESSIONS"
id = "YOUR_SESSIONS_NAMESPACE_ID"
preview_id = "YOUR_SESSIONS_PREVIEW_ID"

# Durable Objects for stateful edge computing
[[durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimiter"

[[migrations]]
tag = "v1"
new_classes = ["RateLimiter"]

# Environment variables
[vars]
ENVIRONMENT = "production"
API_URL = "https://api-penny.railway.app"
JWT_PUBLIC_KEY = "YOUR_JWT_PUBLIC_KEY"

# Build configuration
[build]
command = "npm run build:workers"
watch_paths = ["workers/**/*.ts"]

# Development settings
[dev]
port = 8787
local_protocol = "http"
upstream_protocol = "https"
host = "0.0.0.0"

# Observability
[observability]
enabled = true
logs = { level = "info", sampling_rate = 0.1 }
metrics = { enabled = true }
tracing = { sampling_rate = 0.01 }

# Routes for different workers
[[routes]]
pattern = "penny.ai/api/*"
script = "api-proxy"

[[routes]]
pattern = "penny.ai/auth/*"
script = "auth-worker"

[[routes]]
pattern = "penny.ai/media/*"
script = "media-transform"

[[routes]]
pattern = "cdn.penny.ai/*"
script = "cdn-worker"

# Triggers for scheduled tasks
[[triggers.crons]]
cron = "0 */6 * * *"
handler = "cleanupExpiredSessions"

[[triggers.crons]]
cron = "0 0 * * *"
handler = "generateUsageReports"